### ISSUE TITLE
DB has both "uievents" and "ui-events"

### ISSUE THREAD

**Issue by tabatkins** [tobie/specref#180]
The biblio db has both "uievents" and "ui-events", which aren't aliases of each other, but clearly should be.  If possible, we should keep the "ui-events" name, but this doesn't really matter, and you should use whatever name is easiest for your tools.

(This is currently messing up the bibliography of the DOM spec.)

**Comment by tobie** [comment]
Keeping "uievents" (as that's the W3C shortname), aliasing "ui-events." Landing PR in a few.
