### ISSUE TITLE
[[FULLSCREEN]] should map to fullscreen.spec.whatwg.org

### ISSUE THREAD

**Issue by annevk** [tobie/specref#184]
No other specification is maintained. We could call the other version LEGACY-FULLSCREEN or W3C-FULLSCREEN? Happy to write a pull request for this.

**Comment by tobie** [comment]
So this implies also handling this somehow in the auto-update scripts or it'll get overwritten when the next auto-update kicks in.

**Comment by annevk** [comment]
Can you give me a pointer? Happy to do that.

**Comment by tobie** [comment]
The auto-update scripts are kind of a giant ball of Scotch tape at this point, so I'm not 100% sure what the solution is. Not to mention that W3C has two completely different ways of indicating retired specs, one which I just found out about now. FYI, the file that handles W3C updates is "/scripts/rdf.js".

Simply renaming things doesn't work as it's immediately overwritten by the auto-update script.

Ideally, W3C would publish the specs that are superseding retired specs, but I'm not holding my breath.

I need to think about this a bit more. Would <3 input from @darobin's and @marcoscaceres on this topic.

**Comment by tobie** [comment]
Fixed the isRetired issue in #186. Intend to use this as a way to prevent overwriting.

**Comment by marcoscaceres** [comment]
hmmm... I guess the best thing to do right now is to have a "whatwg-fullscreen" ref. There is no much we can do about W3C squatting "fullscreen" :( I think that will be fine, as the fullscreen spec has been gutted and points anyone who lands there to the right place.

**Comment by tabatkins** [comment]
@marcoscaceres Nah, that's just a short-term solution. As tobie alluded to, when we know that a spec is retired, we can avoid having the auto-updater overwrite a same-name spec from a different source.

**Comment by marcoscaceres** [comment]
Ok, we should work with the w3c team then.

**Comment by tobie** [comment]
Well, we have this data; a bunch of specs--including this one--are already marked as retired. Now we just have to account for this information in order to avoid overwriting references that have been manually modified.

**Comment by tabatkins** [comment]
Looks like it's just a matter of, at `rdf.js:142`, checking if the rdf ref is retired, and the `current` ref is `!isGeneratedByThisScript()`, and only doing the work in that conditional if both of those are false.

**Comment by annevk** [comment]
The alternative is maybe having duplicate metadata? And let the specification decide which set to use? E.g. I noticed [[ENCODING]] is bogus though, listing a W3C editor that is not actually editing. And maybe for WHATWG documents I would just credit the WHATWG, not anyone in particular.

**Comment by tobie** [comment]
@tabatkins something like that (that script is in such a bad state I'm never too sure what effect an actual change has until I actually run the script on the data and compare the output).

@annevk so the problem with [[ENCODING]] is its gathering the data from the W3C tr.rdf file which lists editors as they were indicated on the last WD.

ToDos:
- [ ] fix the W3C import script so it doesn't overwrite content if the reference is marked as retired (@tobie)
- [ ] modify biblio.json so [[FULLSCREEN]] points to the WHATWG version (@tobie).
- [ ] add a reference entry for all WHATWG specs in the form of [[WHATWG-shortname]] \(@annevk, @tabatkins, or @marcoscaceres) (note if the editors/authors were listed on https://spec.whatwg.org/ we could write a script to automate that really easily).

Lastly, I'm also considering adding a W3C-prefixed version of all specs. Like that we'd have:

* [[W3C-FULLSCREEN]] points to the retired NOTE.
* [[WHATWG-FULLSCREEN]] points to the WHATWG spec.
* [[FULLSCREEN]] is aliased to [[WHATWG-FULLSCREEN]].

If you have thoughts on the above, please share them.

**Comment by annevk** [comment]
I'm happy to host a JSON file on resources.whatwg.org that has an overview of all WHATWG documents that you could scrape. Or we could add it to this repository? Automated seems overkill given that we don't actually believe in referencing snapshots.

**Comment by tobie** [comment]
@annevk whatever's more convenient for you. I wasn't intending to reference snapshots, just scrape it daily to automatically reference new specs and modify existing ones in case of a title or editor change. If you're willing to do the work by hand directly in biblio.json, that works too.

**Comment by annevk** [comment]
Can it be a distinct file in this repository that the build script pulls in? That might make it a little bit more convenient to work with while still keeping all references in a single place.

**Comment by tobie** [comment]
Absolutely.

The biblio file needs to split up anyway. It's just too big.

**Comment by tobie** [comment]
Started working on the ref split up here: #187

**Comment by annevk** [comment]
Here's a list of WHATWG publications in JSON: https://gist.github.com/annevk/4e0b98a8846b8e8cf643

I've started thinking that if I add GitHub and Twitter fields to that perhaps Bikeshed can take over part of the header generation... @domenic @tabatkins WDYT?

**Comment by domenic** [comment]
@annevk logo too probably. Would still need customization though; e.g. streams wants "Snapshot as of this commit" link. I guess we could hope that I get around to rolling out that process for all specs though.

**Comment by domenic** [comment]
As for the [[WHATWG-X]] + [[W3C-X]] + pick a default for [[X]], I'd prefer [[X-TR]] + [[X-LS]] or something similar. It's not like we have [[ISO-X]] or [[ECMA-X]].

Also in general I find aliases confusing... Does Bikeshed make sure to convert everyone to a single canonical name first? It'd suck to see some specs reference [[ALIAS1]] and others reference [[ALIAS2]], or worse, both in one spec.

**Comment by annevk** [comment]
Yeah, we should always allow for customization and omitting data (e.g. Media Session does not have authors at the moment). It seems nice to have all that metadata centrally available though.

**Comment by tobie** [comment]
So I've split up `biblio.json` into different files in #187. Now looking at importing WHATWG references in #189.

The aliasing isn't _that_ complicated; an identifier either points directly to the reference object or to another identifier, recursively. All aliases are resolved (there are tests for that) and when you query the API for a reference you always get all the objects necessary to resolve it in the same response. So for example, https://specref.herokuapp.com/bibrefs?refs=rfc7230 responds with:

```json
{
    "rfc7230": {
        "authors": [
            "R. Fielding, Ed.",
            "J. Reschke, Ed."
        ],
        "date": "June 2014",
        "href": "https://tools.ietf.org/html/rfc7230",
        "id": "rfc7230",
        "publisher": "IETF",
        "status": "Proposed Standard",
        "title": "Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing"
    }
}
```

while https://specref.herokuapp.com/bibrefs?refs=HTTP11 gives you:

```json
{
    "HTTP11": {
        "aliasOf": "RFC7230",
        "id": "HTTP11"
    },
    "RFC7230": {
        "aliasOf": "rfc7230",
        "id": "RFC7230"
    },
    "rfc7230": {
        "authors": [
            "R. Fielding, Ed.",
            "J. Reschke, Ed."
        ],
        "date": "June 2014",
        "href": "https://tools.ietf.org/html/rfc7230",
        "id": "rfc7230",
        "publisher": "IETF",
        "status": "Proposed Standard",
        "title": "Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing"
    }
}
```

Which let's you get to the data by using a simple `while` loop over the response. The contract guaranteed by the API is to always let you resolve aliases.

Now whether you decide to display the result as, [HTTP1], [rfc7230], [RFC7230], or even [1] is up to the consumer of the API. Frankly, I don't think it really matters that much. Of course, it's silly to reference both [HTTP1] and [rfc7230] in the same doc, but that's something for the editor and/or his tools to figure out. If the API was using a different structure for the responses (e.g. an array), things could be done differently. Worth considering for a V2.

**Comment by domenic** [comment]
Thanks for explaining the aliasing. I guess then my hope is simply that @tabatkins has Bikeshed resolve all aliases to their original before putting anything in our documents. (So that i.e. [[HTTP11]] and [[RFC7230]] never show up, but instead we get [[rfc7230]] in all Bikeshed documents.)

**Comment by tabatkins** [comment]
I don't think that's well-advised; at least, I couldn't do it for the CSS specs, which are a jumble of naming standards and aliasing.  It would be pretty annoying to type in [[css-images-3]] and have it turn into [[css3-images]] (or something, unsure about this exact example).

I do handle aliases in general, though.  They just get filled in with the data of whatever they're aliasing.

**Comment by tobie** [comment]
Looked into this again today, and it's really complicated. Don't expect a quick resolution, here. Apologies. :(

**Comment by marcoscaceres** [comment]
Can I help? Can you explain a little bit more what needs to be done?

**Comment by tobie** [comment]
Well, we'd like a system that's either manual or automated that let's us handle cases where specs were handled by the W3C but are now handled by WHATWG (that's the current issues, but a generalization of the problem would be better).

Problems:

1. This needs to be a manual process as most W3C specs don't advertise themselves as retired. Actually, only [FULLSCREEN] does atm. There might be other ways to get at this info, but bear with me.
2. Some of these retired specs actually have past references which need to continue existing. That's for example the case with [DOM].
3. This system has to deal with this either at runtime, or during the scripted spec updated but as an extra step once all of the specs have been updated (as we need to be sure that e.g. a WHATWG spec exists to replace a retired W3C spec.
4. A completely different approach might be to add an extra biblio file which would allow to manually override stuff. I don't know how that would work out with the test suite which checks for dups. Nor if we don't risk ending up with a huge file here and/or politics.

**Comment by annevk** [comment]
FWIW, the dated reference in DOM don't actually work. https://dom.spec.whatwg.org/#biblio-uievents-20031107 has the wrong authors, the wrong title and URL, and the correct date and state. It's basically useless and I'm thinking of removing the Goals section since the Goals are accomplished.

**Comment by tobie** [comment]
Yeah, I had to scrounge for this data and what I was given was incomplete. I think manually fixing those in `refs/w3c.json` should work and should not be overwritten. I'll look into it.

**Comment by annevk** [comment]
Don't worry about it. If folks really care they can go through DOM's commit history. Now all those standards are accepted as obsolete it doesn't really matter anymore.
