### ISSUE TITLE
SVG should point to SVG1.1, not SVG1.0

### ISSUE THREAD

**Issue by shepazu** [tobie/specref#188]
Currently, the entry for "SVG" points to the SVG 1.0 spec, with "SVG10" as an alias for that.

The content of the "SVG" entry should be moved to "SVG10", and "SVG" should be listed as an alias for "SVG11".

SVG 1.0 should not be referenced by any modern spec; SVG 1.1 is much better defined. SVG 2 will be better defined still

If you agree to this , I can make the changes.

**Comment by tobie** [comment]
Absolutely. That needs to be handled in the import script, though, as manual changes would be wiped out by the next auto update. Not too sure how to handle it yet, though.

**Comment by tobie** [comment]
#199 exposes the `obsoletedBy` and `obsoletes` properties in the API itself which should let consumers of the API decide what they want to do in that case.
