### ISSUE TITLE
RFCs <1000 have the wrong links (and names?)

### ISSUE THREAD

**Issue by annevk** [tobie/specref#211]
I don't think RFC791 should become RFC0791 and it should certainly not end up linking to https://tools.ietf.org/html/rfc0791 which ends up doing some expensive search before redirecting (I think).

**Comment by tobie** [comment]
That's the identification scheme that the source doc uses: http://www.ietf.org/rfc/rfc-index.xml (warning: large XML file) and from which the [links are built](https://github.com/tobie/specref/blob/ed2c7a3/scripts/rfc.js#L37-L39) (as they're not provided in the XML).

I'm fine adding aliases for RFC[unpadded-num] to RFC[padded-num] (or vice-versa) and making all URLs unpadded.

**Comment by annevk** [comment]
It seems the canonical URLs are all unpadded. I would prefer we adopt that as the canonical pattern, including for identifiers.

**Comment by tobie** [comment]
WFM
