### ISSUE TITLE
DOM Standard links do not use HTTPS?

### ISSUE THREAD

**Issue by annevk** [tobie/specref#217]
In Bikeshed I used `<a spec=dom>ASCII case-insensitive</a>` and it resulted in a URL that did not use HTTPS.

**Comment by tobie** [comment]
Yeah, W3C publishes its specs with HTTP URLs and redirects HTTPS to HTTP. What's your suggestion here?

**Comment by annevk** [comment]
I mean I get links to `http://dom.spec.whatwg.org/` rather than `https://dom.spec.whatwg.org/`. It seems somewhere there is a problem? Not sure about W3C.

**Comment by annevk** [comment]
See also https://github.com/tabatkins/bikeshed/issues/461.

**Comment by tobie** [comment]
So in Specref, [DOM] still points to the W3C version which it'll continue doing until I actually fix #184. If you want to force the WHATWG version use: [WHATWG-DOM].

It looks like bikeshed is somehow aliasing [DOM] to [DOM-LS] and holds an [incorrect reference](https://github.com/tabatkins/bikeshed/blob/ff608218bc3f691cb4b7156437164068b8cd086d/bikeshed/spec-data/readonly/specs.json#L358) to the latter.

Closing this here as there's nothing I can do outside of fixing #184.

**Comment by annevk** [comment]
Thank you @tobie.
