### ISSUE TITLE
Touch Events Level 2 is missing?

### ISSUE THREAD

**Issue by cvrebert** [tobie/specref#228]
Based on https://specref.herokuapp.com/search-refs?q=Touch%20Events and some grepping, there doesn't seem to be an entry for Touch Events Level 2 (https://w3c.github.io/touch-events/) in the DB.

**Comment by tobie** [comment]
http://dvcs.w3.org/hg/webevents/raw-file/v1/touchevents.html redirects to https://w3c.github.io/touch-events/, so linking to [touch-events] will have the right ED.

I agree there should be a clearer transition path, but pretty much every spec which has multiple levels is coming up with its own strategy there so it's hard to find a consistant solution.

For future ref, it's easier to look things up on specref.org, e.g.: http://www.specref.org/?q=touch%20events
