### ISSUE TITLE
TLS for www.specref.org & api.specref.org

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#239]
Would be awesome if we made specref.org secure.

**Comment by tobie** [comment]
Yeah. Figuring out how to do that on heroku, without paying $25/month is a bit complicated.

We'd need to secure both api.specref.org for the API and www.specref.org.

**Comment by annevk** [comment]
From https://sikac.hu/use-let-s-encrypt-tls-certificate-on-heroku-65f853870d90 it seems you need to pay unless you use CloudFlare, which is a bit of a hack.

**Comment by halindrome** [comment]
I have free hosting on dreamhost.  Not sure if it would handle the specref
stuff, but I would be happy to host the domain there if you like.  And it
has free TLS.

On Mon, Feb 29, 2016 at 12:52 AM, Anne van Kesteren <
notifications@github.com> wrote:

> From
> https://sikac.hu/use-let-s-encrypt-tls-certificate-on-heroku-65f853870d90
> it seems you need to pay unless you use CloudFlare, which is a bit of a
> hack.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobie/specref/issues/239#issuecomment-190068843>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by tobie** [comment]
Yeah, getting a cert for specref.org isn't the issue. Getting the certificate for the subdomain that would point to heroku app is.

**Comment by halindrome** [comment]
Okay - well, let me know if I can help.  We have budget for stuff like this.

On Mon, Feb 29, 2016 at 7:53 AM, Tobie Langel <notifications@github.com>
wrote:

> Yeah, getting a cert for specref.org isn't the issue. Getting the
> certificate for the subdomain that would point to heroku app is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobie/specref/issues/239#issuecomment-190221180>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by tobie** [comment]
Well, I guess the cheapest option is just to pay for the heroku's $20/mo fee for TLS in that case. No?

**Comment by halindrome** [comment]
Certainly in the short term.  Longer term there must be a way to get it for
free, but who has the time to figure that out? Happy to do it.  Contact me
directly via shane at spec-ops.io okay?

On Mon, Feb 29, 2016 at 7:57 AM, Tobie Langel <notifications@github.com>
wrote:

> Well, I guess the cheapest option is just to pay for the heroku's $20/mo
> fee for TLS in that case. No?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tobie/specref/issues/239#issuecomment-190222360>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by tobie** [comment]
Sent.

**Comment by tobie** [comment]
Now a one-click install: https://blog.heroku.com/announcing-automated-certificate-management

**Comment by MichielBijl** [comment]
Happy to see this is being worked on :).

**Comment by tobie** [comment]
Yeah, so the API sits behind a cert, now. The doc website, I'll wait for GitHub to follow through.

**Comment by tabatkins** [comment]
Jeezus jumping christ, this isn't your fault, it's Python's, but for anyone stuck on Python 2.7.6 (such as anyone running Ubuntu Trusty, like all Google employees do by default), the biblio update step no longer works.  2.7.6's urllib2 implementation doesn't understand the SNI feature of TLS, which I assume you're using here. :(

**Comment by tobie** [comment]
@tabatkins just revert https://github.com/tabatkins/bikeshed/commit/11d433fa8527de0d1aa96f0921a5a902368ea172. The previous URL still works.

**Comment by tabatkins** [comment]
Oh! I assumed you were deprecating that URL. I'll change it back, thanks!

(Instead, I was planning with @plinss to proxy the URL thru csswg.org, who doesn't use SNI and can still be connected to on old Pythons.)

**Comment by tabatkins** [comment]
Oh, and note that <https://specref.org> has a bad cert.  (<https://api.specref.org> seems fine.)

**Comment by tobie** [comment]
> Oh! I assumed you were deprecating that URL. I'll change it back, thanks!

The idea's simply to abstract the URL away from the hosting provider, so we're free to change provider should the need arise. No plan to do so for now, so using the previous link should buy you quite some time for now.

> Oh, and note that https://specref.org has a bad cert. (https://api.specref.org seems fine.)

Afaik, it has no cert. It's hosted by GitHub pages which doesn't yet support https for custom domains.

**Comment by MichielBijl** [comment]
@tobie you could set up CloudFlare, which wouldn’t get you end-to-end encryption, but still something rather than nothing.

**Comment by tobie** [comment]
@MichielBijl yeah. I probably could do that. :)

**Comment by tobie** [comment]
Closing as specref is now using cloudflare for the www cert.
