### ISSUE TITLE
[META-THEME-COLOR] should become some sort of alias of [HTML]?

### ISSUE THREAD

**Issue by domenic** [tobie/specref#252]
See https://github.com/whatwg/meta-theme-color

Not sure what the best procedure is here. It seems weird to make it a pure alias since then bibliographies will say things like "[META-THEME-COLOR]. HTML. Living Standard. https://html.spec.whatwg.org/multipage/." Maybe delete it and make everyone fix their breakages?

See also https://github.com/w3c/manifest/issues/431.

**Comment by tobie** [comment]
I think the right way to proceed would be to add "[obsoletedBy](https://github.com/tobie/specref/blob/master/schemas/raw-reference.json#L202-L205)": ["HTML"] to the to the META-THEME-COLOR entry.

This let's the tools warn editors appropriately (nudge @tabatkins, @halindrome, @marcoscaceres).

This can be done either in the [WHATWG resource file](https://resources.whatwg.org/biblio.json) or in the [Specref WHATWG ref file](https://github.com/tobie/specref/blob/master/refs/whatwg.json). Your pick.

**Comment by domenic** [comment]
Specref sounds better, since that way we can keep the WHATWG resources file to only contain specs.

**Comment by tobie** [comment]
http://www.specref.org/?q=meta-theme-color

**Comment by tabatkins** [comment]
I don't handle obsoletes/obsoletedBy yet, but I've added [an issue for it](https://github.com/tabatkins/bikeshed/issues/635).

(Are the two guaranteed to be mirrors of each other?)

**Comment by tobie** [comment]
> (Are the two guaranteed to be mirrors of each other?)

No. I'm not checking this data.
