### ISSUE TITLE
Please specify license information

### ISSUE THREAD

**Issue by takenspc** [tobie/specref#263]
https://github.com/tobie/specref states specref is 'An open-source, community-maintained database'.
However I am unable to find license information so that it is hard to reuse specref code and/or data.

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license
>  Generally speaking, the absence of a license means that the default copyright laws apply.

I would like to use this great data, please specify license information. Or please let me know if there is license information.

**Comment by tabatkins** [comment]
I Am Not A Copyright Lawyer, but as this is a database of facts (names/etc of publications), the contents are not actually copyrightable in several countries, including the US.  The organization of the data also likely doesn't constitute a creative exercise (it's trivial and straightforward), so it's likely not protected either.  However, EU law is a bit different, and they do protect "databases" in at least some contexts, so it's worth making the licensing explicit.

That said, I recommend [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by tobie** [comment]
> Often an author creates a work by selecting various public domain components and grouping them together. If the selection, coordination, and arrangement of the material is unique, it will be protected as a copyrightable compilation. Example: The owners of the book Bartlett’s Familiar Quotations selected and arranged famous quotes. Anyone may copy a few quotes from Bartlett’s Familiar Quotations, but no one may copy the selection and arrangement of all the quotes.

From Standford's [Copyright and Fair Use Overview](http://fairuse.stanford.edu/overview/public-domain/trouble-spots/#compilations).

Thus planning to release the data as CC0 and code as Apache 2.0.

**Comment by tabatkins** [comment]
That's discussing a collection of information with creative intent put into the organization; compiling a book of quotations involves choosing which quotations to include, their arrangement in the book, etc. That's a creative work even if you don't write a word of it yourself, same as making art from newspaper clippings.

In at least some countries (like the US), this is distinguished from databases of facts or statistics. The "can't copyright facts" ruling has stood up to many challenges from sports leagues, TV guide producers, and others.

But that all said, it hurts no one to be explicit that it's not intended to by protected by copyright. ^_^
