### ISSUE TITLE
Can / should WICG specs gets added automatically?

### ISSUE THREAD

**Issue by RByers** [tobie/specref#266]
Increasingly new APIs are being specified first in the W3C [WICG](https://github.com/wicg).  I was going to submit a PR to add a couple APIs that are shipping in Chrome (eg. [Intersection Observer](https://github.com/wicg) and [InputDeviceCapabilities](http://wicg.github.io/InputDeviceCapabilities/), but realized it may be better to try to handle this automatically if possible.

**Comment by tobie** [comment]
I <3 automation. What about you just release a JSON file like WHATWG does that I can pole every hour.

**Comment by RByers** [comment]
Ah, I wasn't sure where you got the list - a JSON file makes sense. At the moment I don't think the WICG maintains a list of all it's specs, but perhaps it should. @yoavweiss WDYT, could something (automated or if necessary manual) in the WICG process result in a new specs getting added to a list somewhere that we serve up as JSON for use cases like specref?

**Comment by RByers** [comment]
FWIW it looks like WEB-BACKGROUND-SYNC is the only WICG spec currently in the database.

**Comment by tobie** [comment]
Anything else is fine btw. I could poll GH's API or what not. I don't really care as long as you tell me what it is and abide by it.

**Comment by RByers** [comment]
Thanks.  The main probably is that I don't think there's consistency between different WICG repos (some don't even have specs).  So I think this is really a question for the WICG chairs @yaovweiss and @cwilso.

For example, perhaps the WICG should just encourage everyone to publish specs as index.thml, and you could just look for every WICG repo with an index.html file.  Alternately every WICG repo already has (or should have) a w3c.json file.  Perhaps that could contain a list of spec paths (which defaults to just index.html if unset).

**Comment by tobie** [comment]
Whatever solution has to be maintenance free on this side. I'd also rather face to avoid parsing HTML.

**Comment by cwilso** [comment]
Hmm.  Could be managed with a JSON index in the WICG/admin repo, yes?  Tobie, can you point me at the WHATWG one as an example?

**Comment by tobie** [comment]
- [WHATWG data](https://resources.whatwg.org/biblio.json)
- [WHATWG import script](https://github.com/tobie/specref/blob/master/scripts/whatwg.js)

**Comment by tobie** [comment]
> WEB-BACKGROUND-SYNC

Yup, it was added here: #234.

**Comment by tobie** [comment]
Your move, folks. ;)
