### ISSUE TITLE
Pull external infos about specs from secure sources

### ISSUE THREAD

**Issue by AxelNennker** [tobie/specref#273]
Replace value of RDF_FILE here
https://github.com/tobie/specref/blob/master/scripts/rdf.js#L9
by the https URL:
https://www.w3.org/2002/01/tr-automation/tr.rdf

Consider whether isGeneratedBy needs to be updated too:
https://github.com/tobie/specref/blob/master/scripts/rdf.js#L311

**Comment by tobie** [comment]
WFM. PR welcomed. Please do fix `isGeneratedBy` when you do.

**Comment by tobie** [comment]
Closed by #276
