### ISSUE TITLE
use https://www.w3.org/ where possible

### ISSUE THREAD

**Issue by AxelNennker** [tobie/specref#274]
@w3c updated their infrastructure to https and future references to w3c specs should use https-URLs.

While some of the changes to https might in the future come from an updated https://www.w3.org/2002/01/tr-automation/tr.rdf some APIs of specref might need to be updated to treat https and http URLs as the same.
E.g. http://www.w3.org/TR/2015/WD-FileAPI-20150421/ redirects to https://www.w3.org/TR/2015/WD-FileAPI-20150421/ already.
So specref should treat them as equal and answer queries about FILE_API using the https URL only.

**Comment by tobie** [comment]
Agreed. We want to both fix the import script **and** run a script to update existing references.

**Comment by AxelNennker** [comment]
W3 plans to change the contents of tr.rdf in June. 
I suggest to wait for that to have happened and then look for what might still need to be done here e.g. small things like update the examples in readme.md and bigger changes like updating scripts.

**Comment by plehegar** [comment]
We're delayed for the June switch. Shooting at July now. Here is the proposal:
  https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html

@tobie , please let us know if the change in tr.rdf could break things on your side.

**Comment by tobie** [comment]
@plehegar: Yes, this change seems like it could wreck havoc. Especially the http to https aliasing. I'll need to test this stuff out and adjust scripts. Is it possible for you to have the new tr.rdf staged somewhere so I have time to conduct those tests and transition without breaking stuff?

**Comment by tobie** [comment]
Trying a brute force solution with #286. Let's hope I don't have to roll it back.
