### ISSUE TITLE
WebIDL 2.

### ISSUE THREAD

**Issue by mikewest** [tobie/specref#291]
As @domenic noted in w3c/webappsec-secure-contexts#33, WebIDL maps to WebIDL-1, which has a title of "Web IDL Level 1". I'd actually like to be referencing https://heycam.github.io/webidl/, which is "Web IDL (Second Edition)". Tab pointed me here in https://github.com/tabatkins/bikeshed/issues/750... WDYT, @tobie?

**Comment by tobie** [comment]
@domenic, @mikewest, @tabatkins: wdyt about #292 as a temporary fix to the is problem?

**Comment by mikewest** [comment]
LGTM, thanks!

**Comment by domenic** [comment]
Seems a bit unfortunate given how we have a history of these sort of temporary fixes turning into long term fixes with specref, but better than nothing I guess :-/

**Comment by tobie** [comment]
Yeah. We need a generic way to overwrite stuff.
