### ISSUE TITLE
Web IDL has the wrong title?

### ISSUE THREAD

**Issue by domenic** [tobie/specref#304]
In https://github.com/tabatkins/bikeshed/issues/837 it is claimed that the reason Bikeshed is outputting "Web IDL Level 1" for https://heycam.github.io/webidl/ is

> the name is determined by the W3C, and they say it's called "Web IDL Level 1" in their biblio data

So I guess maybe this is a specref issue?

**Comment by tobie** [comment]
So this is a W3C issue with leveled specs which I've engaged with @deniac to try and solve in a consistent way. There's things I can do manually in specref on a case per case basis. I'll do so here.
