### ISSUE TITLE
add 'FIPS-186-4'

### ISSUE THREAD

**Issue by equalsJeffH** [tobie/specref#305]
bikeshed just told me:
```
FATAL ERROR:\033[0m Couldn't find 'FIPS-186-4' in bibliography data. Did you mean:
  fips-186-3
  fips-180-4
  fips-180-3
  cwg1864
  p0186r0
Did not generate, due to fatal errors
```
FIPS-186-4 is here: http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf

**Comment by tobie** [comment]
References are pretty easy to add: https://github.com/tobie/specref#manual-changes

You could just add it below the [FIPS-180-4](https://github.com/tobie/specref/blob/ee2359a/refs/biblio.json#L993-L997) reference.

**Comment by equalsJeffH** [comment]
was unable to submit patch right away, so sub'd issue so I/we wouldn't fergetabboudit.
