### ISSUE TITLE
Bring back xref support?

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#316]
Can bring back xref support? any reason why it was ripped out?

**Comment by tobie** [comment]
I just have no idea how to keep its data up to date. I also didn't know that anyone was using it.

**Comment by tobie** [comment]
I mean, I ripped it out in March last year and no one complained until now. :)

**Comment by tabatkins** [comment]
It was "maintained" by people periodically manually regenning the files from the WHATWG specs that generated them. It wasn't very good.

Now that WHATWG is converted over to Bikeshed, using the BS database is a better method.

**Comment by tobie** [comment]
Well, it hadn't be modified since [May 16, 2013](https://github.com/tobie/specref/commits/8268cddad409d7172511783ea26474dc29f3b7ed/xrefs.json), so the quotes are perfectly appropriate.

**Comment by marcoscaceres** [comment]
@tabatkins, I'd like to expose the BS database through Specref. Is available as JSON or a real DB that node can interact with? 

@tobie, yeah... only now getting around to adding support in ReSpec. Vacation project.

**Comment by tabatkins** [comment]
Yeah, Bikeshed gets it all from Shepherd as JSON, and just massages it into a format that's slimmer and faster to parse. Check out <https://github.com/tabatkins/bikeshed/blob/master/bikeshed/update.py> for how I use it.

**Comment by marcoscaceres** [comment]
ah, ok... so I can just go directly through "https://api.csswg.org/shepherd/".

**Comment by marcoscaceres** [comment]
@tabatkins, sorry, can you give me one URL example? The documentation produced at  https://api.csswg.org/shepherd/ doesn't make much sense to me :(

**Comment by marcoscaceres** [comment]
Argh, sorry... never mind... it was right there.

**Comment by marcoscaceres** [comment]
(https://api.csswg.org/shepherd/spec/?spec=css-flexbox-1&anchors&draft)

**Comment by marcoscaceres** [comment]
@tabatkins, sorry, one last silly question... any way to get Shepherd to not prefix "var response = "?

**Comment by tabatkins** [comment]
I suspect it has to do with sending the right Accept header (`application/json`), and by default it sends a JS file rather than JSON.

(It didn't used to do this, so I'm bugging @plinss about it.)

**Comment by plinss** [comment]
Yes, the response type is based on the Accept header. I can change that if it's problematic to set.

FWIW, using an Accept of application/json on the api home url gets you a json-home page, see: http://tools.ietf.org/html/draft-nottingham-json-home-03
and https://github.com/plinss/apiclient for an example of how to use it (python), I also have urltemplate handling code in js at https://apidemo.w3ctag.org/uritemplate.js if you need it

**Comment by marcoscaceres** [comment]
Great! Thanks for the clarification, @plinss
