### ISSUE TITLE
Better cache indicators

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#317]
Would it be possible to put in expires information into the responses? This would make ReSpec much faster, as I wouldn't need to hit the network as often.

Additionally, I want to use the expires information to know if I should update a local database with references.

Nice to have: it would be nice if the data for a particular request hasn't been updated, then 304. However, understand that that is much more tricky.

**Comment by tobie** [comment]
> Would it be possible to put in expires information into the responses? This would make ReSpec much faster, as I wouldn't need to hit the network as often.

Sure. What caching strategy would you recommend?

> Additionally, I want to use the expires information to know if I should update a local database with references.

That makes sense though you can already get this information via GH's API: https://api.github.com/repos/tobie/specref/commits?path=refs&per_page=1 
 
> Nice to have: it would be nice if the data for a particular request hasn't been updated, then 304. However, understand that that is much more tricky.

Yeah, that seems non-trivial to setup with the current in memory db system we have. Might be easier to consider migrating the data to a real DB, but then there's a whole bunch of things you need to consider on top of this.

**Comment by marcoscaceres** [comment]
> Sure. What caching strategy would you recommend?

I was thinking that we could just set it based on Expires: every 24 hours. 

> That makes sense though you can already get this information via GH's API:

Ah, that could definitely work (`commit.date`)! It's a little bit of indirection, but can live with it.   

I guess there is no backwards compatible way of adding the above metadata directly into the response file. 

Alternatively, I could get specref to get the above resource, pull out the `commit.date`, and serve it as a the appropriate HTTP header. 

> Yeah, that seems non-trivial to setup with the current in memory db system we have. Might be easier to consider migrating the data to a real DB, but then there's a whole bunch of things you need to consider on top of this.

Yeah... maybe 2018 life goals.

**Comment by marcoscaceres** [comment]
@tobie, so, reading a bit... it seems like we can just: 

```
app.enable("etag");
```

That seems to work for me locally: returning 304s!
