### ISSUE TITLE
Support xrefs via Shepherd

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#320]
Ok, so I had look at the output from Shepherd... unfortunately, the API is not very customizable, leading to massive downloads. For example the HTML spec is 1MB of JSON... and DOM is 400Kb. It's too much to send down to the client (specially phones)... so, what would be great would be to bring in data for known specs into spec ref, then allow smarter queries like:

```
?spec=dom&terms=fire an event,the foo,the bar
```

And get back just the xrefs needed. 

```JSON
{
    "dom": {
      "fire an event": "#concept-event-fire",
      "the bar": null,
     }
}
```

Probably need a bit more detail, like returning the "type" (so to correctly style)... but you get the idea.

**Comment by marcoscaceres** [comment]
Alternatively, Shepherd could support the above... but I have no idea who/where it is maintained, if it's on github, what language it's written in, etc.

**Comment by marcoscaceres** [comment]
@tabatkins would this be of interest to you for BikeShed at all?

**Comment by tabatkins** [comment]
No, Shepherd's current design (just send all the information down) is ideal for Bikeshed, as it creates and uses a full database of its own offline.  I very intentionally designed Bikeshed to not require any network traffic when processing (unless you use one of the optional features that require it).

I'm not sure that getting Bikeshed-equivalent linking out of Shepherd is really possible, without Shepherd reproducing Bikeshed's smart linking logic (which is continually getting tweaked, too).  Cross-spec linking is really incompatible with client-side JS. :/

**Comment by marcoscaceres** [comment]
> On 7 Jan 2017, at 7:59 am, Tab Atkins Jr. <notifications@github.com> wrote:
> 
> No, Shepherd's current design (just send all the information down) is ideal for Bikeshed, as it creates and uses a full database of its own offline. I very intentionally designed Bikeshed to not require any network traffic when processing (unless you use one of the optional features that require it).
> 
> I'm not sure that getting Bikeshed-equivalent linking out of Shepherd is really possible, without Shepherd reproducing Bikeshed's smart linking logic (which is continually getting tweaked, too). Cross-spec linking is really incompatible with client-side JS. :/
> 
Oh! Them's fighting words, Tab. No one questions the honour of my beloved JS! 

Now i have to do it! 😎

But seriously, if the web platform can't do it - then that's an opportunity to fix stuff in the platform. I'm maybe being overly optimistic, but I can't see anything in Shepherd's output that would prevent this from working in JS.

**Comment by tabatkins** [comment]
> But seriously, if the web platform can't do it - then that's an opportunity to fix stuff in the platform.

It's nothing to do with the web platform, it's to do with the economics.  Bikeshed's linking database is large - in my relatively compact specialty format it's 3Mb; in JSON it's some constant factor larger.  You need the whole DB to autolink properly, but you can't ship that over the wire for "live" ReSpec.  If we could pretend that nobody actually deployed live ReSpec, you could just fetch it on each refresh, but we both know that people abuse ReSpec in exactly that way. ^_^

The only alternative is to do all the linking logic on the server-side, so the network chatter is fairly minimal.  But then someone has to reproduce Bikeshed's autolinker, or some approximation to it, and keep that up-to-date.  I'm not particularly interested in doing so. ^_^

**Comment by tobie** [comment]
I haven't looked at the data, but couldn't something similar to what is done for biblio refs be organized? i.e. gather all x-refs, just request those from the API?

**Comment by tabatkins** [comment]
Yeah, but that returns a lot of data potentially.  Unlike biblio refs, where the request info is a unique key that identifies a single resource, in autolinking the linking text often maps to a bunch of different keys.  It's a lot more network chatter than should be necessary, and just makes the problems with live-published ReSpec even worse.

**Comment by marcoscaceres** [comment]
> The only alternative is to do all the linking logic on the server-side, so the network chatter is fairly minimal. But then someone has to reproduce Bikeshed's autolinker, or some approximation to it, and keep that up-to-date. I'm not particularly interested in doing so. ^_^

I'm interested in doing exactly that tho. Yes, it's going to be a big undertaking, so I'll need to see if it's worth it (i.e., number of specs using ReSpec, and if the number is constant, declining, or growing). 

> It's a lot more network chatter than should be necessary, and just makes the problems with live-published ReSpec even worse.

Once the right xrefs get cached locally tho it should be fine, then those can be incrementally updated in the spec's db.

**Comment by marcoscaceres** [comment]
Closed by https://github.com/sidvishnoi/respec-xref-route/
