### ISSUE TITLE
Upgrade links to HTTPS

### ISSUE THREAD

**Issue by edent** [tobie/specref#340]
There are several links in `biblio.json` which don't use `https` where available.

Is it OK for me to go in an change [links like this](https://github.com/tobie/specref/blob/master/refs/biblio.json#L1675) to point to `https` sources where appropriate?

Or do I need to change them in a specific location and regenerate them? Or have I missed the point entirely? :-)

(Was originally https://github.com/tabatkins/bikeshed/issues/966 and https://github.com/w3c/html/issues/832 )

**Comment by tobie** [comment]
You can manually change references that are in biblio.js and legacy.js, for the rest, it's a bit more complicated.
