### ISSUE TITLE
Certain links in biblio.js 404

### ISSUE THREAD

**Issue by tobie** [tobie/specref#342]
As reported by @edent in #341, the following all 404 on both `http` and `https` versions:

* http://www.ce.org/Standards/browseByCommittee_2757.asp
* http://www.ce.org/Standards/Standard-Listings/R4-3-Television-Data-Systems-Subcommittee/CEA-708-D.aspx
* http://www.jpeg.org/cd15444-1.pdf

**Comment by edent** [comment]
Here are some others which are also broken.  There may be more - but hidden behind redirects.

## 401

* https://www.w3.org/Style/Group/css3-src/css3-positioning/Overview.html

Needs authorisation (which I have). Says it should be https://www.w3.org/TR/css-position-3/

## 404

* http://www.signelec.com/content/download/digital_signature_guidelines.pdf
* http://grail.cs.washington.edu/pub/papers/Jacobs2003.pdf
* http://webstore.ansi.org/RecordDetail.aspx?sku=ANSI+X9.44%3a2007
* http://bondi.omtp.org/1.11/security/BONDI_Architecture_and_Security_v1.1.pdf
* http://bondi.omtp.org/1.11/apis/apifeatures.html
* http://www.digitalimaging.org/pdf/wg1n1017.pdf
* http://people.opera.com/richt/release/specs/discovery/Overview.html
* http://codebutler.com/firesheep/
* http://www.scte.org/documents/pdf/standards/SCTE%20193-2%202014.pdf
* http://specs.wacapps.net/2.0/jun2011/deviceapis/sensors.html
* http://www.subtraction.com/pics/0703/grids_are_good.pdf

## Reports 4.01 but redirects

* https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Protocols/NSAccessibility_Protocol/index.html

## Broken

* https://labs.ericsson.com/apis/web-device-connectivity/
