### ISSUE TITLE
Please add payment handler API

### ISSUE THREAD

**Issue by domenic** [tobie/specref#349]
https://w3c.github.io/webpayments-payment-apps-api/

**Comment by tobie** [comment]
Is "payment-apps" the shortname it's going to go by or will that change? There's a note about this, but it's not super clear whether it applies to this shortname or a possible previous one.

**Comment by domenic** [comment]
Um, I dunno, I just want to reference it. @ianbjacobs maybe knows?

**Comment by ianbjacobs** [comment]
Hi all,

I think the shortname is likely to change given that the title has changed. 
We will know for sure within 2 weeks (I am hoping) when we request to go to FPWD.
Can we leave this open until then? (And in the meantime, the current URL is 
https://w3c.github.io/webpayments-payment-apps-api/ )

Ian

**Comment by tobie** [comment]
Looks like this is now: https://w3c.github.io/webpayments-payment-handler/

**Comment by ianbjacobs** [comment]
Yes. 

(We will also have a TR link soon ...but not yet. But you may not need that.)

Thanks!

Ian

**Comment by marcoscaceres** [comment]
Added automagiclaly now that it's FWPD. 
http://www.specref.org/?q=payment-handler
