### ISSUE TITLE
Front-end UI for submitting new entries

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#37]
Doing pull requests is getting old (people's branches fall out of sync... there is a lot of rebasing, etc. and it's kinda silly for a project like this). It would be nice if there was some kind of front end for generating and submitting entries. 

Something like:
http://marcoscaceres.github.io/bib_entry_maker/

Except not crap :)

**Comment by tobie** [comment]
Feel like this is much less of an issue now that most of the content generation has been automated. Closing.
