### ISSUE TITLE
Fix *.idea.whatwg.org URLs, and automate discovery?

### ISSUE THREAD

**Issue by foolip** [tobie/specref#382]
refs/whatwg.json has https://books.spec.whatwg.org/ and https://figures.spec.whatwg.org/ but these now redirect to *.idea.whatwg.org.

Given commit 932cfb575be6f69301b828b60f446366ecb34af9 it looks like there is automation for WHATWG updates, but does it discover new specs? How should we teach it about *.idea.whatwg.org? The status should be "Living Idea".

@tobie @domenic

**Comment by foolip** [comment]
I'm not submitting a PR for this, because once automated it should handle moving between spec and idea.

**Comment by foolip** [comment]
Hmm, wait, I see https://resources.whatwg.org/biblio.json is the source. @annevk @domenic, do we maintain that by hand?

**Comment by annevk** [comment]
Yes, that is maintained by hand at the moment. But any changes there should be picked up by the tooling.

**Comment by foolip** [comment]
OK, I'll try changing it, and then I would expect that at least the "Living Idea" thing needs to be done manually. We shall see.

**Comment by foolip** [comment]
OK, let's see if that works.

**Comment by tobie** [comment]
It does: https://github.com/tobie/specref/commit/a1da2959cab1a81888098561c5a82223022be9ef.

**Comment by foolip** [comment]
Sweet, thanks!
