### ISSUE TITLE
Cross-check against scraped Web IDL specs

### ISSUE THREAD

**Issue by foolip** [tobie/specref#383]
https://github.com/GoogleChrome/webidl-diff is an ongoing project to automatically scrape the Web IDL of Blink, all specs that it link to from its IDL, and all the IDL from Gecko and WebKit. (URLs in Gecko and WebKit aren't considered.)

It seems likely that new specs will occasionally be first discovered by this tooling, or that there are small disagreements about canonical URL and similar between webidl-diff and specref.

@mdittmer, as a one-off to see if there's anything to this, could you list all of the URLs that webidl-currently knows about?

Content: I'm searching for the ultimate list of web specs that matter, and my best bet right now is that filtering the specref database will provide that list.

**Comment by tobie** [comment]
> Content: I'm searching for the ultimate list of web specs that matter, and my best bet right now is that filtering the specref database will provide that list.

I'd suggest getting the top-level directories (and the directories in https://github.com/w3c/web-platform-tests/tree/master/css) from the wpt repo, thank putting those into [specref.org](http://specref.org) to get the URLs, or directly using the [API](https://github.com/tobie/specref#get-a-set-of-bibliographic-references).

Alternatively, if you have URLs there's an [API tied to a reverse lookup table](https://github.com/tobie/specref#reverse-lookup), which you can also access from [specref.org](http://specref.org), e.g.: <http://www.specref.org/?q=https%3A%2F%2Fdrafts.csswg.org%2Fcss-display>.

**Comment by dr-shorthair** [comment]
>  I'm searching for the ultimate list of web specs that matter

I doubt if it exists, or could exist. Specs that matter are published in too many different places, some quite informal. e.g. JSON was just a website for a long time. And not everyone understands or even believes that documentation counts ...

**Comment by tobie** [comment]
>> I'm searching for the ultimate list of web specs that matter
> I doubt if it exists, or could exist.

I think @foolip meant the list of specs that represent technology currently implemented (or in the process of being implemented) in Web browsers with reasonable interoperability.

**Comment by foolip** [comment]
> I think @foolip meant the list of specs that represent technology currently implemented (or in the process of being implemented) in Web browsers with reasonable interoperability.

That is correct. Seems like the list doesn't exist, but I'm growing it for https://foolip.github.io/day-to-day/

**Comment by tobie** [comment]
You're welcome to annotate Specref if that's helpful. We can create an extra property for this on the spec reference and expose it (e.g. a boolean or URL to the test suite).

**Comment by foolip** [comment]
What I think I'll end up doing is scraping the specs themselves for links to test suites to handle cases where the shortnames don't match. Is any Specref data currently based on the links to the specs, and would it be a problem if it took many hours to process all specs?

**Comment by tobie** [comment]
> What I think I'll end up doing is scraping the specs themselves for links to test suites to handle cases where the shortnames don't match.

Mmm. It feels like getting the few offending specs fixed is less work, here, but I might be wrong.

> Is any Specref data currently based on the links to the specs,

No if by this you're asking whether I'm already getting data out of scrapping the specs themselves.

> and would it be a problem if it took many hours to process all specs?

Yeah, the update script is run hourly, so this would cause issues.

It could be run separately on a 24h schedule, though. Note that this runs on Heroku, so there might be certain restrictions as to what exactly you can run there (I know getting phantomjs to run there was non trivial for example).

**Comment by foolip** [comment]
Let me just try to work around the mistmatched names and fix a few of them, maybe it'll be fine.

This issue was originally really just about cross-checking if @mdittmer's tooling would discover any spec URLs that Specref doesn't know about, and if so adding them somehow. That'd give me more confidence that "ultimate spec list" is a subset of Specref.

**Comment by tobie** [comment]
> That'd give me more confidence that "ultimate spec list" is a subset of Specref.

That'd be the goal (at least for me). :)

**Comment by tabatkins** [comment]
Related: if, in finding this "ultimate spec list", you find ones that aren't in Bikeshed's db (<https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/specs.json>), it would be *great* to inform me; they need to be added to Shepherd so Bikeshed can cross-link with them.

(This applies whether they're Bikeshed specs or not, but obviously getting Bikeshed specs into Shepherd is an *even higher* priority. But any ol' spec can probably be handled by Shepherd; it uses some pretty good heuristics to extract definitions from them.)

**Comment by foolip** [comment]
One way to go about this that doesn't require @mdittmer's tooling is to just list all URLs that exist anywhere in Gecko, Chromium and WebKit. Filter a bit, and one should be able to at least discover new w3c.github.io specs. (Just listing all repos in the w3c org would do that as well, of course.)

**Comment by tobie** [comment]
Closing this. Feel free to reopen if this is still something you care about.
