### ISSUE TITLE
Expose publisherIdentifiers in specref output

### ISSUE THREAD

**Issue by dr-shorthair** [tobie/specref#388]
The schema now has fields for **rfcNumber**, **isoNumber** and **ogcNumber** (and there may be more to come for series from other organizations). These numbers are often used in the community as alternatives to the textual title of specs, and customarily appear in citations, but they are not exposed in the specref output. 

I don't understand the specref/respec architecture in order to suggest how this could be accomplished, and I don't have the JS skills to implement anyway, but can probably describe requirements and evaluate solutions. 

See https://github.com/tobie/specref/pull/375 and https://github.com/tobie/specref/pull/387#issuecomment-330841537

**Comment by tobie** [comment]
Hey, @TabAtkins and @marcoscaceres, would you be interested to display this data? If so, would you like those differrent identifiers tied into a single property name (e.g. .publisherId or similar).

**Comment by marcoscaceres** [comment]
I'm still not sure what value this brings to readers. @dr-shorthair, let's take a citation from today, and maybe you can tell us what you would like to see differently? 

Given: 
```
The key words may, must, must not, recommended, should, and should not are to be interpreted as described in [RFC2119].
```

It is rendered as:

![screenshot 2017-09-21 17 31 12](https://user-images.githubusercontent.com/870154/30683979-c09506ec-9ef2-11e7-8789-16c8dea681a0.png)

And in the the Reference section, we see:

```
[RFC2119]
Key words for use in RFCs to Indicate Requirement Levels. S. Bradner. IETF. March 1997. Best Current Practice. URL: https://tools.ietf.org/html/rfc2119
```

Which is rendered and linked as: 

![screenshot 2017-09-21 17 32 20](https://user-images.githubusercontent.com/870154/30684011-e9cc9d86-9ef2-11e7-877e-804fb541be71.png)

What would change with `rfcNumber`, `isoNumber` and `ogcNumber`?

**Comment by tabatkins** [comment]
Marcos asked what I was going to ask, but with more examples. ^_^

If the info leads to better biblio display, or easier biblio linking, great. If it doesn't, I don't care what you do.

**Comment by tobie** [comment]
I'm not planning to expose this data unless they are use cases for doing so. Not seeing any, I'll just close this for now. Please feel free to reopen if there use cases show up.

**Comment by dr-shorthair** [comment]
@marcoscaceres argument applies iff the **specref** key is more or less the same as the publisher identifier.

In the case of ISO and OGC specs I don't think this can work for a couple of reasons. 

1. Community expectations around keys
2. The identifier syntax

Here's the details - 

### 1. Keys

Probably best to explain through examples.

In https://www.w3.org/TR/vocab-ssn/ you can find the following (two different places) -

> The returned XML data conforms with the Sensor Model Language [**SensorML**] and OMXML [**OMXML**]

> following the patterns specified in ISO 19109 Geographic Information - Rules for Application Schema [**ISO-19109**].

Most OGC standards and some ISO standards are known in the community primarily by a well known acronym, such as **GML** or **MPEGDASH** (both in biblio.json) or **OMXML** (see example above). People writing specs in the community expect to use the acronym as the key, as shown. But these acronyms are frequently not part of the title, and also do not correspond with the publisher identifier. So the keys people will search for in **specref** and also expect to use as the citation anchor don't actually match the `ogcNumber` or `isoNumber`. 

An additional wrinkle with ISO Standards is that they get replaced periodically, so the current `isoNumber` for the one mentioned above is **ISO 19109:2015**, though the earlier one from 2005 is still cited and had exactly the same title (different URL of course).

In both cases the publisher identifier is an important element in the citation, though it may not be represented either in the title or as the acronym everyone uses as the key. 

### 2. Identifier syntax 

OGC identifiers look like this:

**OGC 07-036r1**

and ISO Identifiers look like this:

**ISO 19109:2005** or **ISO DIS 19156:2010** or **ISO/IEC 23009-1:2014** etc.

i.e. they include spaces, colons, hyphens, which I think are not allowed in JSON names.
Now I acknowledge that this probably wouldn't clinch the argument by itself, as they might just be converted down or squashed to the JSON name gamut. But mangled identifiers would represent a drift from the formally recognized and community expected identifiers maybe a bit too far.

### The case for showing the publisher identifier 

Within a citation, for ISO standards the ISO number usually appears before the title, and for OGC standards the OGC document number is usually buried in the back. So model citations will look something like this:

**[ISO-19109]**
ISO 19109:2015 Geographic information -- Rules for application schema. International Organization for Standardization. December 2015. URL: [https://www.iso.org/standard/59193.html](https://www.iso.org/standard/59193.html)

)**[OMXML]**
Observations and Measurements - XML Implementation. S.J.D. Cox. Open Geospatial Consortium. OGC 10-022r1 2010. URL: [http://portal.opengeospatial.org/files/41510](http://portal.opengeospatial.org/files/41510)

I certainly agree that **specref** does not need to track every publisher's citation preferences - some of them are daft, or clearly self-serving, or way too heavy. So I'd be reasonably content with a single pattern for dealing with all publisher identifiers (I had thought @tobie was leaning that way). Nevertheless, if there are large sets where we *do* know the expected pattern, and if the specref/respec pipeline could support it, then perhaps it could be accomplished? 

Note that there are 100s of ISO standards that are relevant to tech applications particularly when you consider all the ISO/IEC ones, and there are probably more than a 100 from OGC that are actively cited by other tech organizations. As you noticed, we added a bunch of the ISO specs into the dataset in `biblio.json`, and there is at least one OGC spec **[gml]** there as well. These give a flavour of what should be in separate `iso.json` and `ogc.json` files in due course (definitely agree with you there!). With reference to my reference to versioning above, in `biblio.json` the name "ISO-19109" is aliased to the 2015 version "ISO-19109-2015", but "ISO-19109-2005" is also in the dataset, because, depending on the use-case, it might be necessary to refer either to a dated version or just to the 'current' version.

---
Sorry for the delay in responding to request for more information - I was at a conference in Montreal this week, and had to give 6 talks in 3 days so wasn't able to respond until now. Currently in transit LAX. 

And as soon as I get back to Oz I'll be offline (out of cellphone range even) for two weeks. So if this is still unclear we'll have to deal with it after.

**Comment by marcoscaceres** [comment]
> Most OGC standards and some ISO standards are known in the community primarily by a well known acronym, 

This is handled by `aliasOf`. 

> I certainly agree that specref does not need to track every publisher's citation preferences

Correct. Specref has nothing to do with citation styles. That's handled by ReSpec or BikeShed... but it's mostly 🤷🏽‍♂️. In the last 10 years, citation styles have only been raised as an issue once in ReSpec, AFAIK... and by only one user. See https://github.com/w3c/respec/issues/857.  

For references in digital documents, the primary thing people need is the ability to click on links to get to the primary source - where numbers go, comas, dashes, full stops, etc. in citation styles have limited value in a digital document that can hyperlink to things.

Having said that, I'm happy to add support for new citations styles in ReSpec - so long as someone describes the citation rules formally in JS (https://github.com/w3c/respec/issues/857). It's fairly trivial to do it and I'm always available to mentor that work.

**Comment by tobie** [comment]
Wel, LMK what kind of data you'll want for https://github.com/w3c/respec/issues/857 and we can look how best to expose it here.

**Comment by marcoscaceres** [comment]
> Wel, LMK what kind of data you'll want for w3c/respec#857 and we can look how best to expose it here.

I'm still not sure we need anything, tbh. We could just have a rule like:

```JS
if (ref.publisher === "iso") {
  `${ref.status}. ${ref.title}. ${ref.publisher} ${ref.pubDate}`;
}
if (ref.publisher === "OGC") {
  `${ref.title}. ${ref.publisher} ${ref.pubDate}. ${ref.status}.`;
}
```

But given that we have `isoNumber` I guess we can just use it... but we should change the schema to `stdNumber`... The number (or id, really) is dependent on the publisher, so you don't need `isoNumber`, "ogcNumber", because an ISO spec is not going to ever have an `ogcNumber`, right?

**Comment by tobie** [comment]
I think your `stdNumber` is what I was referring to with `publisherId`. Open to bikeshedding this. Do we want to merge ISBN in there too, or is that something else?

**Comment by marcoscaceres** [comment]
Ah, I misunderstood. I thought `publisherId` was an identifier for the publisher, not the publication. That might confuse people, like me. 

Maybe `publicationId`?

**Comment by tobie** [comment]
> I thought publisherId was an identifier for the publisher, not the publication. 

Duh!

Yeah, `publicationId` is better.

**Comment by marcoscaceres** [comment]
So, pondering a bit more, I still feel there is little value `publicationId` for our readers. Sorry  @dr-shorthair. I suggest we close this and reopen if new/interesting use cases emerge.

**Comment by dr-shorthair** [comment]
Thanks @marcoscaceres - I agree that more thorough use of `aliasOf` could be part of the solution to my use-case. 

Note that my suggestions here were based on what I thought was just a logical extension of the existing `rfcNumber` field. However, if `rfcNumber` is only ever used as a duplicate of the spec key (or an alias) then is it really needed? If not, then this thread is maybe a wild-goose chase - i.e. if I misunderstood the function of `rfcNumber`, I may have been extrapolating too far when I added `ogcNumber` and `isoNumber`. 

---
I've just scanned the discussion at w3c/respec#857 and agree that tuning up biblio-styling is the goal here. I'm sorry that I don't fully understand the puzzle pieces here, but you can only style what you are given. I thought that some styling requirements needed the `publicationId` elements, which was why I thought it was a specref job.

**Comment by marcoscaceres** [comment]
> Note that my suggestions here were based on what I thought was just a logical extension of the existing rfcNumber field. 

I totally understand your perspective - but the main driver for including additional data has to be driven by functionality (e.g., "We add X, and we also make it possible to search for X") or representation (e.g., "We add X, and it vastly improves the usability of bibliographical style Y"). 

> I'm sorry that I don't fully understand the puzzle pieces here, but you can only style what you are given. I thought that some styling requirements needed the publicationId elements, which was why I thought it was a specref job.

We are always playing a balancing act between adding more properties and actually making use of those properties. Sometimes we add well intentioned things (e.g., `rfcNumber`), and we just simply don't end up finding any time to actually use them.

**Comment by dr-shorthair** [comment]
1. Winding back to https://github.com/tobie/specref/issues/388#issuecomment-331372594 the thing that I first noticed in the data was what looked like mis-use of the `status` field for a publisher's document ID - status and identifier are orthogonal concerns. 

2. Not quite true that some specs won't be in series from more than one publisher. There are joint publications. ISO 19156:2011 (not free) is also published as OGC 10-004r3 (for free!) - there is an additional cover page pasted on top so it could be argued that they are different artefacts, though the normative content is identical. And a couple of recent W3C specs https://www.w3.org/TR/vocab-ssn/ and https://www.w3.org/TR/owl-time/ also have OGC numbers on the front page. I don't think JSON allows you to repeat fields unless they are in an array. 

3. However, I suspect a major part of the tension here is that I straddle the tech and academic worlds. Citations (and biblio styles) are a big deal in the latter, and there is a lot of prior art and expectation, even business models, around this. OTOH, just being able to get to the content is usually the only thing that matters to the former. You can try to partition the use-cases but the boundary is somewhat porous. 

Suggest we park this for the time being - the datasets have slightly improved content. If or when anyone is motivated to tackle the downstream use of them we can take another look.
