### ISSUE TITLE
FXTF drafts point to dev.w3.org which redirects

### ISSUE THREAD

**Issue by foolip** [tobie/specref#389]
In w3c.json there are a number of edDraft references:
* http://dev.w3.org/fxtf/compositing-1/
* http://dev.w3.org/fxtf/css-masking-1/
* http://dev.w3.org/fxtf/filters/
* http://dev.w3.org/fxtf/geometry/
* http://dev.w3.org/fxtf/matrix/

These all redirect to https://drafts.fxtf.org/compositing-1/ and similar. It looks like the source of the data is https://www.w3.org/2002/01/tr-automation/tr.rdf. How can this be fixed?

Maybe redirects could be automatically detected and flagged for review by the auto-updater?

**Comment by foolip** [comment]
filters actually redirects to https://drafts.fxtf.org/filter-effects/, so it's not just search/replace.

**Comment by tobie** [comment]
You can replace those manually here: https://github.com/tobie/specref/blob/master/overwrites/w3c.json

**Comment by foolip** [comment]
I had it fixed in https://www.w3.org/2002/01/tr-automation/tr.rdf, already auto-updated here.

**Comment by tobie** [comment]
Even better!
