### ISSUE TITLE
Use more HTTPS

### ISSUE THREAD

**Issue by foolip** [tobie/specref#390]
Not sure about the source, but these two real specs redirect to HTTPS:
* http://app-uri.sysapps.org/
* http://drafts.csswg.org/css-overflow/

**Comment by tobie** [comment]
Fixable in different ways depending on where the refs are located. Fixing redirects aren't a huge priority tbh.

**Comment by foolip** [comment]
http://drafts.csswg.org/css-overflow/ is from https://www.w3.org/TR/css-overflow-3/ which is no longer the latest, so closing this.
