### ISSUE TITLE
Reverse lookup on XHR should return WHATWG version, not TR Note

### ISSUE THREAD

**Issue by tidoust** [tobie/specref#450]
A reverse lookup on the XHR spec URL `https://xhr.spec.whatwg.org/` yields information about the W3C XHR Note, whereas I would expect to get some info about the WHATWG spec:
```
https://api.specref.org/reverse-lookup?urls=https://xhr.spec.whatwg.org/
```

Right now, it returns the same info as:
```
https://api.specref.org/bibrefs?refs=xmlhttprequest
```

... and I would rather expect to get the same info as:
```
https://api.specref.org/bibrefs?refs=xhr
```

I haven't looked at the code, but given that the `https://xhr.spec.whatwg.org/` URL is also the URL of the Editor's Draft of the W3C Note, I would suspect that the code simply returns the first match on the requested URL it finds in the database. Reverse lookup is somewhat fuzzy by definition, but I think it should give priority to specs whose URL matches the requested one, and only return specs whose Editor's Draft URL matches the requested one as a fallback.

**Comment by tobie** [comment]
Oh, that's a tough one. Generally, URLs are supposed to be unique, so something weird must have happened there. Maybe the logic doesn't check for the duplicates between the `edDraft` and `href` properties?

**Comment by tidoust** [comment]
I looked at the code and prepared a PR accordingly. The logic seemed to be _willing to_ check for duplicates, but was not doing it properly in practice...
