### ISSUE TITLE
List of top specs

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#467]
I'm wondering, do we have any stats of the most popular cited specs? I'm guessing no, but might be interesting to know. 

Use case: I'm thinking of baking, say, the top N most used citations directly into ReSpec (and then checking if they are stale, and updating them as needed - means a big perf improvement for ReSpec users). 

There are obvious stable candidates, like RFC2119, WebIDL, HTML, DOM, etc.  but would be interesting to see what else people are citing a lot (e.g., 95% of specs cite X). 

cc @sidvishnoi, who I've discussed this with.

**Comment by tobie** [comment]
Specref is used very differently by Bikeshed (downloads the whole DB every time you run `bikeshed update`) and Respec (hits the API for every new visitor). I don’t see how we could reconcile this and get. Alia le data out of it. What you want to do is crawl the specs for links instead and use Specref’s reverse lookup table to find the ones which are specs.

**Comment by marcoscaceres** [comment]
Yeah, makes sense. Will see if I can do as you suggested instead.

**Comment by tabatkins** [comment]
@tobie Just FYI, `bikeshed update` doesn't do that anymore, but the script that *generates* the databases for `bikeshed update` does, once every ten minutes.  A user calling `bikeshed update` now just grabs the specific changed files they need directly from [the bikeshed-data repo](http://github.com/tabatkins/bikeshed-data).

@marcoscaceres Note that Bikeshed now does comprehensive regression testing on every W3C/WICG/WHATWG spec, which means that all of those specs are now checked into Bikeshed's repository (in the `tests/github` folder) and available for crawling for whatever purpose you need. I'm about to start doing exactly that to figure out how to start getting cross-spec dfn-panels working.

**Comment by tobie** [comment]
That's awesome. Thanks for the update, @tabatkins.

**Comment by marcoscaceres** [comment]
@tabatkins that's excellent. Although we are still in the planning phase of @sidvishnoi GSoC project, it's likely we will end up using BikeShed's data for our cross referencing too. We are still evaluating how all the pieces slot together, and if we need to set up a web service for ReSpec to query xref data. 

If you have more information about the "cross-spec dfn-panels", and if we can collaborate in some way, we'd really like to be part that.

**Comment by tabatkins** [comment]
Like cross-referencing in general, I doubt this feature is compatible with ReSpec's client-side nature. But the idea is that, right now, you can click on a definition and get a panel to pop up listing all the places in that spec that reference the definition. I'm just going to extend it to point to all the places *in all other specs I can find* that reference it as well.

**Comment by marcoscaceres** [comment]
> Like cross-referencing in general, I doubt this feature is compatible with ReSpec's client-side nature. 

We are planning to do the heavy lifting on the server, and then just send data down to the browser (either as JSON or "server rendered" HTML). 

> But the idea is that, right now, you can click on a definition and get a panel to pop up listing all the places in that spec that reference the definition. I'm just going to extend it to point to all the places in all other specs I can find that reference it as well.

That also sounds doable by querying a server, and then streaming results down to the browser.  Wouldn't the same model benefit BikeShed? Otherwise, won't you need to  pre-compute all the those relationships and then ship all that data down with each spec?

**Comment by marcoscaceres** [comment]
cc @saschanaz, who is interested in this also.

**Comment by marcoscaceres** [comment]
Ok, we will keep that in mind and make sure we don't send unnecessary data.
