### ISSUE TITLE
WG21 P0646R1 became untitled in automatic update

### ISSUE THREAD

**Issue by foolip** [tobie/specref#474]
Noticed this when looking at something else entirely. In commit 79a71edffe2826a6d9ec26341ec6cc8b2552b615:
```diff
     "P0646R1": {
-        "title": "Improving the Return Value of Erase-Like Algorithms I: list/forward list",
+        "title": "(Untitled)",
         "href": "https://wg21.link/p0646r1",
         "publisher": "WG21",
         "source": "https://wg21.link/index.json"
```

However, https://wg21.link/index.json still has "Improving the Return Value of Erase-Like Algorithms I: list/forward list" as the title for this document, suggesting that something might be wrong with the updating process?

**Comment by tobie** [comment]
FIxed itself. Closing.
