### ISSUE TITLE
Add reference to WHATWG Web sockets spec

### ISSUE THREAD

**Issue by mavgit** [tobie/specref#477]
SpeRef includes [websockets], which points to the 2012 W3C CR [WebSocket API](https://www.w3.org/TR/websockets/) spec, which tells folks to use the WHATWG Web Sockets spec: https://html.spec.whatwg.org/multipage/web-sockets.html#network

We need a SpecRef entry that points to the WHATWG Web sockets spec.

**Comment by tobie** [comment]
It's in the [Network section](https://html.spec.whatwg.org/multipage/web-sockets.html#network) of the HTML spec itself, so just reference it as [HTML].
