### ISSUE TITLE
"npm test" rejects ' ' in URL but "fetch-refs" puts it there

### ISSUE THREAD

**Issue by sandersaares** [tobie/specref#528]
Example URL: `https://www.scte.org/SCTEDocs/Standards/ANSI_SCTE 01 2015.pdf`

I try to add references like this but `npm test` complains that this is not a valid URL. Because of the space characters. Okay, so I fix it to use %20 - works for me. But then if I try to add an update script, fetch-refs adds the space back in original form.

I think "npm test" should accept space in URLs.

**Comment by tobie** [comment]
That seems like something that needs to be fixed in the module that fetch-refs loads.

**Comment by tobie** [comment]
I think my suggestion in #529 fixes that? Feel free to reopen otherwise.

**Comment by sandersaares** [comment]
I agree, it fixes the issue or at least works around it for this specific case. I am not sure if rejecting spaces is the best path in terms of compatibility - many things seem to consider spaces fine without escaping - but I suppose that is a secondary topic.
