### ISSUE TITLE
Stale data?

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#532]
Seems the WICG and W3C data might be a little stale?... looking at the commit logs, W3C was only updated 6 days ago and WICG was 20 days ago (both datasets have had updates since then). @tobie, maybe an update script is stuck somewhere?

**Comment by tobie** [comment]
Yes. Will take a look shortly. Sorry for the issue.

**Comment by tobie** [comment]
Fixed. A typo in an added automated script.

**Comment by marcoscaceres** [comment]
Yay! Thanks so much!
