### ISSUE TITLE
Wrong date for the "Writing Promise-Using Specifications" TAG Finding

### ISSUE THREAD

**Issue by ylafon** [tobie/specref#537]
https://www.specref.org/?q=promises-guide show 16 February 2016 as the publication date while the target URL is dated 9 November 2018. How is the date maintained for TAG finding in specref? (so that I can update it myself as needed)

**Comment by tobie** [comment]
Manually here, apparently: https://github.com/tobie/specref/blob/master/refs/biblio.json#L4381
