### ISSUE TITLE
WICG specs have a wrong status

### ISSUE THREAD

**Issue by yoavweiss** [tobie/specref#548]
I noticed that WICG specs all have a "Living standard" status which seems wrong. Would it be possible to modify that to something along the lines of "incubation" or "proposal"?

Happy to PR to whatever value you think would be most appropriate!

/cc @cwilso @marcoscaceres @travisleithead

**Comment by tobie** [comment]
Good point. We’d need to fix it in the script and maybe also in some of the older references. Happy to help with the PR or even write it once we’ve settled on the correct term (isn’t there a sanctioned W3C term for this?).

**Comment by marcoscaceres** [comment]
The closes in w3c parlance is "cg-draft" or just "unofficial".

**Comment by yoavweiss** [comment]
"cg-draft" SGTM
