### ISSUE TITLE
DOMHighResTimestamp seems missing

### ISSUE THREAD

**Issue by yoavweiss** [tobie/specref#552]
Not sure if this is an issue here or upstream but `DOMHighResTimestamp` now seems missing from the DB. (High-res-time, where it is defined, can still be found)

Is this a specref issue? If not, can you point me to where the issue is coming from?

**Comment by tobie** [comment]
References don't ever get removed from Specref, so you were maybe relying on a local biblio?

**Comment by yoavweiss** [comment]
I don't think I was, and this is an issue we're now seeing in multiple specs (for those built with Respec, they started erroring out. Trying to build a spec with Bikeshed, linking to DOMHighResTimestamp doesn't compile)

A few related issues on the related Respec specs: https://github.com/w3c/performance-timeline/issues/136, https://github.com/w3c/resource-timing/issues/212

**Comment by tobie** [comment]
Oh! That's an issue with Shepherd. /cc @plinss.

**Comment by marcoscaceres** [comment]
This is actually a Shepherd issue, not Specref.

**Comment by marcoscaceres** [comment]
@yoavweiss, will get these fixed... we need to get the Web Perf specs indexed by Shepherd. We've been working up to that.

**Comment by yoavweiss** [comment]
@marcoscaceres - Thanks!

**Comment by plinss** [comment]
hr-time-2 is being indexed by Shepherd, and there's an entry for DOMHighResTimeStamp in the anchor database. It's currently categorized as a plain 'dfn', adding a `data-dfn-type=typedef` would be good.

**Comment by marcoscaceres** [comment]
@plinss, thanks! The /TR/ snapshot is currently missing the `data-dfn-type=`, but those are now automatically added by ReSpec. Once the spec is republished on /TR/, the correct annotations will be there (hi @plehegar 👋). 

@plinss, how often does Shepherd pick up changes to TR? Do we need to do anything to ping you/Shepherd when we republish?

**Comment by plinss** [comment]
Shepherd looks for changes in all the specs it monitors every day just after midnight pacific time. It also scans them all after any csswg spec update on github so it may pickup changes sooner.

**Comment by plehegar** [comment]
I pushed an update for HRT2. Let's see tomorrow if the problem gets fixed.

**Comment by plinss** [comment]
Shepherd sees it as a `typedef` now (did a manual update)

**Comment by plehegar** [comment]
and specref.org/xref sees it. Looks like we're back in business!
