### ISSUE TITLE
tc39.github.io redirects to tc39.es/ 

### ISSUE THREAD

**Issue by contrepoint** [tobie/specref#560]
Passed the [Web App Manifest url](https://www.w3.org/TR/appmanifest/) into W3C's [link checker](https://validator.w3.org/checklink?uri=https://www.w3.org/TR/appmanifest/&recursive=on) and found this redirect for ECMA-402. 

I will update the link in a PR

```  Line: 6529 https://tc39.github.io/ecma402/ redirected to https://tc39.es/ecma402/ Status: 301 -> 200 OK This is a permanent redirect. The link should be updated. ```

ETA: updated issue title to reflect @tobie's observation below. thank you!

**Comment by tobie** [comment]
Sounds like all GitHub hosted TC-39 specs should be affected by this, no? Think you could do a broader PR and either check the links yourself or get someone from TC39 to approve it?

**Comment by tobie** [comment]
Also, please note that the deployment pipeline is currently down because of a broken update and your changes won’t be deployed until Friday.

**Comment by contrepoint** [comment]
@tobie yes - that is true, thanks for pointing it out! I'll make another PR tomorrow to update the links for the other tc-39 specs.

**Comment by tobie** [comment]
Awesome, thanks!
