### ISSUE TITLE
HR-TIME should be an alias for the latest HR-TIME

### ISSUE THREAD

**Issue by domenic** [tobie/specref#571]
https://www.specref.org/?q=HR-TIME shows `[HR-TIME]` as obsolete, but the DOM Standard needs to be able to refer to the latest HR-TIME ED at https://w3c.github.io/hr-time/ in some way. I would assume `[HR-TIME]` could be that reference, with e.g. `[HR-TIME-1]` being the obsolete one.

**Comment by tobie** [comment]
Heh. That's yet again another one of the same issue of W3C not being consistent with their versioning scheme. You might be able to fix that using overwrites. @marcoscaceres attempted a solution in https://github.com/tobie/specref/pull/564 (although for CSS specs only). But it came with its own set of issues.

The only real solution moving forward would be to enforce a consistent data model in Specref and force W3C specs into it. I don't think anyone really wants to do the work for this, though.

**Comment by domenic** [comment]
Do you have advice for what we should do in the DOM Standard in the meantime? I'd guess, switch to using `[HR-TIME-2]`, and update it every time a new edition comes out?

I guess part of the weirdness is that Bikeshed is complaining at us about using "obsolete" refs, but at the same time using Bikeshed's "prefer latest specs" option means that the obsolete URL never shows up, only the ED URL. /cc @tabatkins

**Comment by tobie** [comment]
> Do you have advice for what we should do in the DOM Standard in the meantime? I'd guess, switch to using [HR-TIME-2], and update it every time a new edition comes out?

Yeah. This sucks. I agree.

**Comment by domenic** [comment]
It's frustrating that when I try that, Bikeshed lists the bibliography entry as "High Resolution Time Level 2. URL: https://w3c.github.io/hr-time/", but when I click on that URL, the title is just "High Resolution Time". More of a Bikeshed issue though, I guess...

**Comment by domenic** [comment]
I guess what's really missing here is an entry in specref that is "Editor's Draft only", which Bikeshed could use when in the `Default Ref Status: current` mode. That would have a title derived from the ED, instead of the TR counterpart.

The problem is now specref is keying off of TR documents, so when a spec author wants to reference an ED, they have to pick a random corresponding TR document and tell Bikeshed to use that specref entry. Bikeshed then dutifully uses that specref entry's title field ("High Resolution Time level 2"), plus its ED URL field (https://w3c.github.io/hr-time/), which causes a mismatch when the ED title and TR title are different.

**Comment by tobie** [comment]
Those are good points.

**Comment by ExE-Boss** [comment]
In&nbsp;fact, the&nbsp;<https://www.w3.org/TR/hr-time/>&nbsp;URL is&nbsp;an&nbsp;alias for&nbsp;<https://www.w3.org/TR/hr-time-2/> (and&nbsp;eventually <https://www.w3.org/TR/hr-time-3/>, once&nbsp;that&nbsp;becomes a&nbsp;**W3C&nbsp;Recommendation**).

It’s&nbsp;<https://www.w3.org/TR/hr-time-1/> that&nbsp;links to&nbsp;the&nbsp;obsolete&nbsp;spec.

**Comment by annevk** [comment]
@plehegar is this something you can solve on the W3C side? To ensure hr-time always points to the latest version rather than being obsolete?

**Comment by tobie** [comment]
I think @ExE-Boss's work is getting us really close to not only have a solution for this particular instance, but also be able to solve this very issue easily more broadly.

**Comment by plehegar** [comment]
I did catch the fact that our API was broken and didn't do versioning properly:
 https://github.com/w3c/w3c-api/issues/96

ie while https://www.w3.org/TR/hr-time/ points to hr-time-2, the API points to the obsolete version of hr-time-1. The fix that that we have to encode the redirects in the DB rather in .htaccess file that the DB doesn't understand.

@tobie , is that the reason why specref gets misled?

**Comment by plehegar** [comment]
I expect this to be fixed no later than January btw.

**Comment by domenic** [comment]
Thank you very much @ExE-Boss; I didn't really expect this to be solvable, but you saved us!
