### ISSUE TITLE
specworker bot out of office?

### ISSUE THREAD

**Issue by tidoust** [tobie/specref#581]
Last commit from specworker was on [17 December 2019](https://github.com/tobie/specref/commit/24d4fd35d944d72f4c5fa6cb01576b388f82673e) and there have been a number of updates since then. Update scripts run fine on my local machine.

Any button that could be pushed to make the bot run again?

**Comment by tobie** [comment]
There’s some conflict somewhere that needs to be addressed. Running the test suite should tell you what. I usually pick those up quickly and fix them, but I have been travelling a lot and my SSD died in the middle of that. My replacement laptop, a Chromebook, doesn’t have a dev env setup and so I couldn’t do much about it.

**Comment by tidoust** [comment]
Ah, got it. I had run `npm test` before running the update scripts, which obviously didn't reveal much...

`web-share` seems to be the issue here. It still appears as a WICG spec but has also been published to /TR/ (on 17 December 2019...). I'll have it removed from WICG's biblio.

**Comment by ExE-Boss** [comment]
There’s&nbsp;also some&nbsp;bug with&nbsp;aliases in&nbsp;`scte.json` not&nbsp;getting processed&nbsp;correctly, causing&nbsp;schema&nbsp;validation&nbsp;failures.

**Comment by tidoust** [comment]
Web Share API fix on its way, see https://github.com/WICG/admin/pull/89.
I see the schema validation issues as well. Will look into them.

**Comment by tobie** [comment]
You can update it here right away by using an overwrite file for wicg with the following action:

```json
[
  { "id": "web-share", "action": "delete" },
 ]
```

**Comment by tobie** [comment]
Had missed your PR. Thanks @ExE-Boss!

**Comment by tobie** [comment]
> There’s also some bug with aliases in `scte.json` not getting processed correctly, causing schema validation failures.

The error messages of the JSON-schema validator are a bit weird. This probably simply implies a schema violation. Not obvious by perusing the file, tbh. Do you have the exact error available?

**Comment by ExE-Boss** [comment]
The&nbsp;issue is&nbsp;that <code>{&nbsp;"aliasOf":&nbsp;"scte..."&nbsp;}</code> gets&nbsp;replaced&nbsp;with <code>{&nbsp;"publisher":&nbsp;"scte",&nbsp;"source":&nbsp;"..."&nbsp;}</code>:

```
  1) Validate References
       Validate References with JSON schema.:

      AssertionError [ERR_ASSERTION]: 
* Data does not match any schemas from "oneOf"
    {
        "publisher": "scte",
        "source": "https://dashifspecref.blob.core.windows.net/scte/scte.json?st=2019-04-01T00%3A00%3A00Z&se=2039-04-01T00%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=eIrXcpSm6WkcgRNBgNKlyMnIUGWLwgTurzYy8K2WApI%3D"
    }
* Missing required property: aliasOf
    {
        "publisher": "scte",
        "source": "https://dashifspecref.blob.core.windows.net/scte/scte.json?st=2019-04-01T00%3A00%3A00Z&se=2039-04-01T00%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=eIrXcpSm6WkcgRNBgNKlyMnIUGWLwgTurzYy8K2WApI%3D"
    }
* Invalid type: object (expected string)
    {
        "publisher": "scte",
        "source": "https://dashifspecref.blob.core.windows.net/scte/scte.json?st=2019-04-01T00%3A00%3A00Z&se=2039-04-01T00%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=eIrXcpSm6WkcgRNBgNKlyMnIUGWLwgTurzYy8K2WApI%3D"
    }
* Missing required property: title
    {
        "publisher": "scte",
        "source": "https://dashifspecref.blob.core.windows.net/scte/scte.json?st=2019-04-01T00%3A00%3A00Z&se=2039-04-01T00%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=eIrXcpSm6WkcgRNBgNKlyMnIUGWLwgTurzYy8K2WApI%3D"
    }
```

**Comment by tobie** [comment]
The import script needs to account for aliases.

**Comment by tobie** [comment]
…so I imagine a new `else if` clause in [here](https://github.com/tobie/specref/blob/74ee876befdd5c23565ba62822d66a216ea8592a/scripts/fetch-refs.js#L43-L58).

**Comment by tidoust** [comment]
The specworker bot seems to have successfully resumed its work. That's all good!
The temporary overwrite file is no longer needed, see #585.
