### ISSUE TITLE
Mismatch between Bert's and Specref's data model?

### ISSUE THREAD

**Issue by tabatkins** [tobie/specref#60]
Bert's biblio.ref file, which forms the basis of Specref from the history in the README, has several more pieces of data than appears possible to document in Specref.

In particular, the %I (Issuer) metadata shows up in several entries that don't otherwise have authors.  Several have %O (Other) as well, though this appears to be mostly (entirely?) used to denote things that aren't yet Recs.

In total, when I last checked, all the following Refer codes were used at least once in Bert's file:

```
        "B": "bookName",
        "C": "city",
        "D": "date",
        "I": "issuer",
        "J": "journal",
        "L": "linkText",
        "N": "numberInVolume",
        "O": "other",
        "P": "pageNumber",
        "R": "reportNumber",
        "S": "status",
        "T": "title",
        "U": "url",
        "V": "volumeNumber",
        "X": "abstract",
        "A": "authors",
        "Q": "foreignAuthors",
```

Not all of these are necessary (I have no clue why Refer separates A and Q, for example), but several sound reasonable, particularly when referring to specific things outside of the specs we publish.

**Comment by tobie** [comment]
Think that has been mostly addressed in #162.

Closing.
