### ISSUE TITLE
Updates to ISO3166 for 2020 revisions

### ISSUE THREAD

**Issue by ianbjacobs** [tobie/specref#648]
Hi folks,

@samuelweiler pointed out [1] that the Payment Request API references to ISO3166-1 and ISO3166-2 have been superseded.

I see there have been three updates:

   https://www.iso.org/standard/63545.html -> https://www.iso.org/standard/72482.html
   https://www.iso.org/standard/63546.html -> https://www.iso.org/standard/72483.html
   https://www.iso.org/standard/63547.html -> https://www.iso.org/standard/72484.html

This is a request to update specref references to ISO3166-1, 2, and 3.

@aphillips and @r12a, do you think there's a use case for stable references to the 2013 versions?

cc @samuelweiler, @marcoscaceres

Thanks!

[1] https://github.com/w3c/payment-request/issues/945

**Comment by aphillips** [comment]
@ianbjacobs I don't. In general, most users are more interested in the code lists than the text of these specifications.

**Comment by marcoscaceres** [comment]
Sent a pr https://github.com/tobie/specref/pull/649
