### ISSUE TITLE
Make [WEBSOCKETS] point to WHATWG spec, not dead W3C spec

### ISSUE THREAD

**Issue by domenic** [tobie/specref#689]
https://www.specref.org/?q=websockets points to https://www.w3.org/TR/websockets/, which redirects to https://html.spec.whatwg.org/multipage/

It should instead point to https://websockets.spec.whatwg.org/, per https://resources.whatwg.org/biblio.json

**Comment by tobie** [comment]
Lol. That's where all of those PR-Preview errors were coming from earlier today.

**Comment by tobie** [comment]
That's one of these painful changes like: https://github.com/tobie/specref/pull/686
