### ISSUE TITLE
W3C Process doc missing from W3C data

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#701]
It appears that the [w3c process doc](https://www.w3.org/Consortium/Process/) is missing as reference. 

Should I add it to biblio.json or can we somehow get it to be added automatically to w3c.json (would be best)?

**Comment by tobie** [comment]
Either should work

**Comment by marcoscaceres** [comment]
For the automatic option, do you know off the top of your head where the W3C comes from? I can then go and ask people at the w3c to get it added.

**Comment by tobie** [comment]
Sorry. Misread your question. Automated content in `w3c.json` comes from `tr.rdf`. So you’ll have to add the file manually.
