### ISSUE TITLE
Unable to reference new mediaqueries-3 REC

### ISSUE THREAD

**Issue by mattgarrish** [tobie/specref#706]
We had a reference in the epub 3.3 specification to `css3-mediaqueries` that lists the 2012 version as the current recommendation, but a new recommendation was published on April 5: https://www.w3.org/TR/mediaqueries-3/

I tried changing the reference to `mediaqueries-3` but this had no effect as it appear to be an alias.

I'm not familiar enough with how the specref database gets updated to say what the problem is, but I also noticed that the w3c.json file in the refs directory hasn't been updated in 16 days, which would be before the new recommended version was released.

Is there an issue with getting the latest data from W3C, or is the problem perhaps caused because an alias has already been assigned to the shortname used for the new recommendation? A little bit of each? Or am I way off base?

/cc @iherman

**Comment by tobie** [comment]
> is the problem perhaps caused because an alias has already been assigned to the shortname used for the new recommendation?

Yes! That has broken the auto-update mechanism and I haven’t had the time to look into it.

**Comment by mattgarrish** [comment]
Is it as easy as stripping this entry from the biblio.json file: https://github.com/tobie/specref/blob/6b142be84d2758249423aa81bbd6f8e4501b289e/refs/biblio.json#L2072

The danger I assume is that if someone really only wants to reference the 2012 version this would bump them forward, but is that a problem in practice?

**Comment by frivoal** [comment]
> On Apr 22, 2022, at 2:17, Matt Garrish ***@***.***> wrote:
> Is it as easy as stripping this entry from the biblio.json file: https://github.com/tobie/specref/blob/6b142be84d2758249423aa81bbd6f8e4501b289e/refs/biblio.json#L2072 <https://github.com/tobie/specref/blob/6b142be84d2758249423aa81bbd6f8e4501b289e/refs/biblio.json#L2072>
> The danger I assume is that if someone really only wants to reference the 2012 version this would bump them forward, but is that a problem in practice?
> 

Shouldn’t be an issue, these two specs are normatively equivalent. The new one has editorial tweaks, and annotations indicating proposed (therefore not yet accepted as normative) corrections. Except for explicit comparison, (and in that case, they should be referred to with dated drafts), there’s no reason to specifically want to refer to the old one.

**Comment by tobie** [comment]
Fixed in #709.

**Comment by mattgarrish** [comment]
Thanks!
