### ISSUE TITLE
[IAccessible2] resolved to an unknown page

### ISSUE THREAD

**Issue by jnurthen** [tobie/specref#710]
From looking at what was on the old resource from archive.org (https://web.archive.org/web/20160122032422/http://www.linuxfoundation.org/collaborate/workgroups/accessibility/iaccessible2 ) 

this should now resolve to

https://wiki.linuxfoundation.org/accessibility/iaccessible2/

**Comment by jnurthen** [comment]
Also AT-SPI is invalid - searching for the new ref for that too

**Comment by jnurthen** [comment]
AT-SPI should resolve to https://developer-old.gnome.org/libatspi/stable/

**Comment by jnurthen** [comment]
will create a PR once specref clones

**Comment by jnurthen** [comment]
@tobie Thanks for merging. Is there a timeframe that these will be live in specref? I still see the old URLs being returned.

**Comment by tobie** [comment]
It normally is right away except there’s currently a broken update that needs manual fixing. So as soon as I get to it.
