### ISSUE TITLE
Specref might be stuck?

### ISSUE THREAD

**Issue by marcoscaceres** [tobie/specref#748]
Seems the bot stopped 5 days ago...

https://github.com/tobie/specref/commits/main

@tobie, when you can, can you give it restart?

**Comment by tobie** [comment]
Saw this. But was traveling. It doesn’t update because of a conflict. We need to figure out what the conflict is and then fix. Will try to do so asap.

**Comment by gkellogg** [comment]
Thanks for filing, @marcoscaceres.

**Comment by tobie** [comment]
Hopefully fixed in 41f24e7ace35a251e584c158cbac81e67c09b326.

**Comment by gkellogg** [comment]
Yes, looks good! Thanks.
