### ISSUE TITLE
Browserspec script is removing entries

### ISSUE THREAD

**Issue by tobie** [tobie/specref#752]
The browser spec script is removing entries (currently `TC39-RESIZABLEARRAYBUFFER`) which (rightfully) breaks the build.

Script needs editing to keep those references around and potentially mark them as obsolete.

**Comment by tobie** [comment]
No rush, I commented out the script in the update script, so it's not blocking anything. Please uncomment it as part of the pull request to fix this issue.

**Comment by tidoust** [comment]
Noted. I'll look into it! I knew that this would bite us at some point (see https://github.com/w3c/browser-specs/issues/1006), I was just hoping that it would bite us later ;)

We've happily killed entries of discontinued specs in browser-specs until now, we need to have a better mechanism in place.

This particular TC39 proposal stayed in Specref for a few weeks at max. I thought dropping it could still be viewed as acceptable. I had not realized that there was a check on that part of the contract during the Specref build. It certainly makes sense ;)

Ideally, the entry should also have an `obsoletedBy` property to note the integration into ECMAScript.

Another recent example is the [Close Watcher API](https://wicg.github.io/close-watcher/), which is currently transitioning to HTML.

**Comment by tobie** [comment]
So normally, the update script has that somewhat built-in. I'm not sure what you did for this not to happen.

**Comment by tidoust** [comment]
Both WICG and browser-specs contain spec proposals that are meant to transition to some other source at some point. Such transitions may incur a change of shortname. When that happens, the mechanism that you mention in the update script may leave "ghost" entries that would better be replaced with an `aliasOf` relationship, for instance:

- [Resize Observer](https://www.specref.org/?q=resize-observer). It exists in Specref as `resize-observer`, which links to the WICG version, and `resize-observer-1`, which links to the /TR version. Ideally, the WICG entry would rather point at the more current /TR version through an `aliasOf` property.
- [Scroll Animations](https://www.specref.org/?q=scroll-animations). Same thing, it exists in Specref as `scroll-animations`, which links to the WICG version, and `scroll-animations-1`, which links to the /TR version.

It's quite possible that these are the only occurrences of the issue. I dropped the mechanism to avoid any possibility to end up with further occurrences in `browser-specs.json`. I'm now adding mechanisms to browser-specs to make sure that deletions can't happen anymore and that we can create the right `aliasOf` and `obsoletedBy` properties. I should be able to craft a PR that leverages this and fixes this issue early next week.

By the way, is there a conceptual difference between `isRetired` and `isSuperseded`? Which one should I use when I set an `obsoletedBy` property?

**Comment by tobie** [comment]
> Both WICG and browser-specs contain spec proposals that are meant to transition to some other source at some point. Such transitions may incur a change of shortname. When that happens, the mechanism that you mention in the update script may leave "ghost" entries that would better be replaced with an `aliasOf` relationship, for instance:

Yeah, you're not wrong in those cases. In practice the problem is there are lots of outliers and no single solution that works in all cases.

> It's quite possible that these are the only occurrences of the issue. I dropped the mechanism to avoid any possibility to end up with further occurrences in `browser-specs.json`. I'm now adding mechanisms to browser-specs to make sure that deletions can't happen anymore and that we can create the right `aliasOf` and `obsoletedBy` properties. I should be able to craft a PR that leverages this and fixes this issue early next week.

To be clear, your upstream can do whatever it wants. We just don't want to delete old entries here.
 
> By the way, is there a conceptual difference between `isRetired` and `isSuperseded`? Which one should I use when I set an `obsoletedBy` property?

I think `isRetired` means the thing defined by the spec is no longer relevant whereas `isSuperceded` means that the thing defined by the spec continues to be relevant but is defined in a new spec. So I assume `isSuperceded` should be used with `obsoletedBy`.
