### ISSUE TITLE
Portable Network Graphics (PNG) still refers to old version (2003)

### ISSUE THREAD

**Issue by svgeesus** [tobie/specref#758]
A [specref search for PNG](https://www.specref.org/?q=PNG) resolves **[PNG]** to the old, 2003 Second Edition. 

There is also an explicit [PNG2e] which is an alias to [PNG], and assorted dated references to [PNG third edition](https://www.w3.org/TR/png-3/) which is currently a Candidate Recommendation and has [a bunch of new features, clarifications and corrections](https://www.w3.org/TR/png-3/#F-ChangeList) compared to the second edition.

Instead, [PNG 2e] should alias to the dated second edition, and there should be a [PNG 3e] which aliases to the latest.

On the W3C TR page, going to /TR/PNG takes you to the third edition.

I know that the data from /TR is [auto updated](https://github.com/tobie/specref#hourly-auto-updating) so I assume something on the W3C side is not correctly indicating that the third edition supersedes the second edition. I would like to get this cleared up and assume that manual editing is not the correct way forward here as it will get overwritten?

**Comment by tobie** [comment]
Thanks, @deniak for the help fixing this!
