### ISSUE TITLE
Broken link to Open Web Foundation Agreement Version 1.0 

### ISSUE THREAD

**Issue by phochste** [tobie/specref#791]
I'm using Bikeshed to create specs and I noticed that in every document the links to the Open Web Foundation Agreement are broken as can be seen in the headers of:

- https://w3c-cg.github.io/rdfsurfaces/
- https://semiceu.github.io/LinkedDataEventStreams/
- https://speced.github.io/bikeshed/

> To the extent possible under law, the editors have waived all copyright and related or neighboring rights to this work. In addition, as of 8 March 2024, the editors have made this specification available under the [Open Web Foundation Agreement Version 1.0](http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0), which is available at http://www.openwebfoundation.org/legal/the-owf-1-0-agreements/owfa-1-0. Parts of this work may be from another specification document. If so, those parts are instead covered by the license of that specification document.

@tabatkins refers to this project for a solution to this problem.

See also: https://github.com/speced/bikeshed/issues/2509

**Comment by tobie** [comment]
I think that this is actually a Bikeshed boilerplate issue and that the files that need to be fixed are those two: Could this be a Bikeshed boilerplate issue and the files needing to be fixed be those: https://github.com/search?q=repo:speced/bikeshed-boilerplate+Open+Web+Foundation+Agreement&type=code. @tabatkins, can you infirm/confirm? Thanks!

**Comment by tobie** [comment]
Fixed in bikeshed.
