### ISSUE TITLE
Missing specs that are used in AOM

### ISSUE THREAD

**Issue by podborski** [tobie/specref#792]
Here are a few specifications that we are missing from [AV1 spec](https://aomediacodec.github.io/av1-spec/#bibliography):

- SMPTE ST 170 (2004), Television – Composite Analog Video Signal – NTSC for Studio Applications.
- SMPTE ST 240 (1999), For Television – 1125-Line High-Definition Production Systems – Signal Parameters.
- IEC 61966-2-1 (1999), Multimedia systems and equipment – Colour measurement and management – Part 2-1: Colour management – Default RGB colour space – sRGB.
- ISO/IEC 23091-4/ITU-T H.273, Coding-independent code points for video signal type identification.
- ITU-R BT.2100 : Image parameter values for high dynamic range television for use in production and international programme exchange

**Comment by podborski** [comment]
Note that the referencing any ITU-R documents should include the ITU-R prefix

**Comment by alexismt73** [comment]
It should also be ISO/IEC 23091-2, not 4. Part for is a technical report on usage. Also better to use a "|" to separate the ISO/IEC and the ITU-T variants. This is what is used elsewhere:

Rec. ITU-T H.273 | ISO/IEC 23091-2.

**Comment by alexismt73** [comment]
Also the CICP specification does not include a "Color primaries" section. It is spelled in that document as "Colour primaries". We should likely use the "variables" ColourPrimaries  since then there is no ambiguity (and as is done in Rec. ITU-T H.274), e.g. use something like:

```
color_primaries is a variable that indicates the chromaticity coordinates that correspond to the color primaries of the source. Its allowed values and semantics are as specified for the ColourPrimaries parameter in Rec. ITU-T H.273 | ISO/IEC 23091-2.

Example allowed values include: ....
```

**Comment by tobie** [comment]
Feel free to submit a pull request !
