### ISSUE TITLE
GPC has an old URL in browser-specs.json even though it's been updated in browser-specs

### ISSUE THREAD

**Issue by jyasskin** [tobie/specref#836]
https://github.com/tobie/specref/blob/ec6a2d1b88be80b80c081dedebfc6ad8650bae50/refs/browser-specs.json#L816-L817

vs

https://github.com/w3c/browser-specs/blob/84d679ee0ffdb1f35c4db2e29596b641d5c6d214/index.json#L19831-L19844

Perhaps the rename from `gpc-spec` to just `gpc` is confusing things?

**Comment by tidoust** [comment]
Auto-update broke a month ago due to some unrelated update conflict. That was fixed last week and the `GPC-SPEC` entry in `browser-specs.json` was correctly updated to become an alias of `GPC` (defined in `w3c.json`).
